# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          # Set a SSH private key from repository secret value for pushing to the remote branch.
          deploy_key: # optional
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          github_token: # optional
          # Set a personal access token for pushing to the remote branch.
          personal_token: # optional
          # Set a target branch for deployment.
          publish_branch: # optional, default is gh-pages
          # Set an input directory for deployment.
          publish_dir: # optional, default is public
          # Set an destination subdirectory for deployment.
          destination_dir: # optional, default is 
          # Set an external repository (owner/repo).
          external_repository: # optional
          # If empty commits should be made to the publication branch
          allow_empty_commit: # optional, default is false
          # If existing files in the publish branch should be not removed before deploying
          keep_files: # optional, default is false
          # Keep only the latest commit on a GitHub Pages branch
          force_orphan: # optional, default is false
          # Set Git user.name
          user_name: # optional
          # Set Git user.email
          user_email: # optional
          # Set a custom commit message with a triggered commit hash
          commit_message: # optional
          # Set a custom full commit message without a triggered commit hash
          full_commit_message: # optional
          # Set tag name
          tag_name: # optional
          # Set tag message
          tag_message: # optional
          # Enable the GitHub Pages built-in Jekyll
          enable_jekyll: # optional, default is false
          # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
          disable_nojekyll: # optional, default is false
          # Set custom domain
          cname: # optional
          # Set files or directories to exclude from a publish directory.
          exclude_assets: # optional, default is .github
